### ISSUE TITLE
Your Golang code is broken

### ISSUE THREAD

**Issue by Abdul-Muiz-Iqbal** [alee-and-muiz/bots#3]
![image](https://user-images.githubusercontent.com/67752771/114982872-653b9f80-9ea9-11eb-9377-662fcae31904.png)
I am pretty sure we haven't lived for 297yrs now.

**Comment by Abdul-Muiz-Iqbal** [comment]
The problem seems to be in the switch statement. Maybe. I hate time.

**Comment by aleeazam** [comment]
Nah. @uimp was blocked, which is why his details are no longer available to the API.
We're going to delete this repository anyway.

**Comment by aleeazam** [comment]
There, I buried @uimp.

**Comment by Abdul-Muiz-Iqbal** [comment]
Ok.
